### ISSUE TITLE
Quality selection not grabbing highest available

### ISSUE THREAD

**Issue by Robert-Janssen** [lejacobroy/Tidalrr#12]
When I add an artist to Tidalrr and perform a scan, it grabs in most cases the 16-bit 44.1 high quality version. Even when a 24-bit version of the album is available. So unless I add the specific 24-bit release of the album manually it won't get picked up.

For example, when adding bastille to my artists list, it grabs this album:
https://tidal.com/browse/album/243863332
But there is a max quality version available:
https://tidal.com/browse/album/243864035

I can guess it has something to do with which albums are presented on the artist page, because to get to this max quality version you have to first click on the high quality one and then at the bottom click through to it.

**Comment by lejacobroy** [comment]
The API Keys available currently dosen't yet allow to stream MAX versions of albums.
The code is there to handle it once we can extract a MAX-capable API Key from the official Tidal app.
