### ISSUE TITLE
Lidarr sync does not queue tracks for download

### ISSUE THREAD

**Issue by jankuca** [lejacobroy/Tidalrr#13]
I wanted to use this to download missing tracks to Lidarr but the Lidarr sync does not work properly. It seems to only populate the `tidal_albums` table but not the `tidal_artists` and `tidal_tracks`.

When I manually add Tidal URLs of the artists and tracks for the albums added by the Lidarr sync, it starts downloading. The Lidarr sync should do this automatically.

**Comment by cedvan** [comment]
Same problem on my system, tidal artist missing, need create it manually to start download albums added by lidarr sync. 

Adding artist manually add this with monitoring disabled. But in scan step all artists albums added. So monitoring system not working with artists.

So, is not possible to download only missing albums in Lidarr in actual state 😞 .

**Comment by cedvan** [comment]
To fix this problem, lidarr scan must create missing artists linked in missing albums, but add this artists with monitoring disabled by default.

A best solution will be sync artist and albums from lidarr, and map monitoring state with lidarr monitoring. So need auto add/monitoring/remove data in tidalrr from lidarr sync

**Comment by cedvan** [comment]
Fixed with PR : https://github.com/lejacobroy/Tidalrr/pull/15
@jankuca You can try waiting merge with image "cedvan/tidalrr:latest"

**Comment by lejacobroy** [comment]
Good point, thanks for the PR, i'll check that out!

**Comment by lejacobroy** [comment]
I'Ve merged the PR, i'm building and pushing the updated docker image right now.
