### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by lieferant** [lejacobroy/Tidalrr#19]
In the read me section a sample docker-compose file is referenced. Unfortunately I can't find one. Could you provide a sample docker-compose file? Many thanks!

**Comment by sickify1** [comment]
https://github.com/lejacobroy/Tidalrr/blob/master/docker-compose-example.yml

The sample file is located here.

**Comment by lejacobroy** [comment]
fixed in https://github.com/lejacobroy/Tidalrr/commit/06dd70cb97007869a64701afb87c9de03f00ddb7
