### ISSUE TITLE
Issue With Quality Higher Than Subscription

### ISSUE THREAD

**Issue by sickify1** [lejacobroy/Tidalrr#2]
I have quality set to the default in settings (I believe it is Max, but would have to clear my DB to check)

I am getting the following when performing a scan after uploading a file for artists who I believe have "Masters" available, I only have a lossless sub.

`setting lower quality
User cannot stream, you must have an active subscription
Error getting stream URL:  Get operation err!Requested quality is not allowed in user's subscription
Error scanning track:  local variable 'stream' referenced before assignment`

The issue is those tracks keep on repeating on the scan, will even stick around for a new scan. But also, my quality in the settings gets set to normal. So if I am downloading at the same time I start downloading low quality mp4's(around 3-4 MB), but it still tries to convert them to flac, but fails saying ffmpeg is not installed or there is an issue with it. It then creates a .flac file of 0 bytes for every song. I had a long queue setup last night and awoke this morning to find 90% of them are low quality mp4's.

I can give specific URL's that this occurs for if needed, just not sure how much can be shared here.

Thank you!

**Comment by lejacobroy** [comment]
When a user doesn't have the subscription for the quality configured, the app will downgrade the saved quality settings for future scans.

If you already scanned a bunch a url with a higher-than-allowed quality and you attempt to download those streams, every file downloaded will try to downgrade the configured quality when they are refreshing their stream url. This will result in the lower quality set in the settings and files downloaded.

To fix the problem, you should remove all the entries in the tidal_queue table (`delete * from tidal_queue`), set the highest quality allowed per your subscription and finally, rescan your urls.

**Comment by sickify1** [comment]
Sorry, I forgot to reply back on this.

The issue was I had just a regular HiFi subscription, with quality set to Max I could download lossless, but if an artist had a higher quality available it would set me down to a low quality for all future downloads, and I would no longer get flac's at all just the low quality ~3MB mp4's.

I resolved this by upgrading my mebership to HiFi Plus, and never got a chance to try after you patched things, so unsure if the issue is still present.
