### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Shinta360** [lejacobroy/Tidalrr#27]
any chance could someone upload a video setting this up via docker and windows 11 
new to docker and cant seem to access the webui

not sure if im missing a config file or missing a step , or is there a better guide 

downloaded docker and pulled the file 
ive opened ports in firewall 
and keep getting 

""Hmmm… can't reach this page172.17.0.2 took too long to respond
Try:

Search the web for [172 17 0 2](https://www.bing.com/search?form=ANLKDR&q=172%2017%200%202)
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_TIMED_OUT""

**Comment by lejacobroy** [comment]
172.17.0.1 seems to b the local docker network address.
Try to reach it with http://localhost:3001 (or the port configured beforehand)
The how to is written here : https://github.com/lejacobroy/Tidalrr#start-everything

**Comment by Shinta360** [comment]
still dont know what and why i cant connect 

This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED


i even asked copilot and it cant figure it out 

any chance anyone can create a youtube video so i can visually see any steps or error im doing wrong or missing 

untill then im giving up 3 days trying 

new to docker and apparently dont know what im doing 
`2024-09-15 23:53:58 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
2024-09-15 23:53:58  * Running on all addresses (0.0.0.0)
2024-09-15 23:53:58  * Running on http://127.0.0.1:3001
2024-09-15 23:53:58  * Running on http://172.17.0.2:3001
2024-09-15 23:53:58 Press CTRL+C to quit
2024-09-15 23:34:50 Starting web server
2024-09-15 23:34:50  * Serving Flask app 'tidalrr.webserver'
2024-09-15 23:34:50  * Debug mode: off
2024-09-15 23:46:29 Starting tidalrr app
2024-09-15 23:46:29 Scans are scheduled
2024-09-15 23:46:29 Downloads are scheduled
2024-09-15 23:46:29 Non-Empty Access Token, logging in
2024-09-15 23:46:29 Starting web server
2024-09-15 23:46:29  * Serving Flask app 'tidalrr.webserver'
2024-09-15 23:46:29  * Debug mode: off
2024-09-15 23:53:57 Starting tidalrr app
2024-09-15 23:53:57 Non-Empty Access Token, logging in
2024-09-15 23:53:57 Scans are scheduled
2024-09-15 23:53:57 Downloads are scheduled
2024-09-15 23:53:58 Starting web server
2024-09-15 23:53:58  * Serving Flask app 'tidalrr.webserver'
2024-09-15 23:53:58  * Debug mode: off
`

**Comment by Shinta360** [comment]
this is my docker composs
`version: '3.7'

services:
  tidalrr:
    container_name: test1
    image: jacobroyquebec/tidalrr
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PUID=501
      - PGID=501
      - WEB_PORT=3001
    ports:
      - 3001:3001
    volumes:
      - "./config:/app/tidalrr/database/config"
      - "./download:/app/download"
      - "./import:/app/import"
      #- /path/to/lidarr/folders:/path/to/lidarr/folders
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock`

**Comment by lejacobroy** [comment]
Don't take this the wrong way, but GitHub is for developper to contribute on code and enhance the product in an open-source way, not to provide help to unskilled users. If you need help on docker, you should reach out to docker forums.

As for your problem, the docker-compose file seems fine.
In your first statement, you didn't specify the port you're using to correct to localhost, so maybe the problem is there.

From the log you added, we can clearly see the port is 3001, hence, you should try to browse to "http://localhost:3001" or "http://127.0.0.1:3001".

Again from the log, Tidalrr is working fine. If that dosen't work still, your problem is elsewhere and I can't help you further, sorry.

**Comment by Shinta360** [comment]
all good no worries 
i used Portainer to setup Docker/Container and it working now 
i tried running again via just docker and still having issues, dont know why im doing same via docker vs portainer 
its working now 
so thanks either way for compiling and creating this software

**Comment by lejacobroy** [comment]
Glad you got it working!
