### ISSUE TITLE
DB Initialization Does Not Create Config Directory

### ISSUE THREAD

**Issue by sickify1** [lejacobroy/Tidalrr#4]
Forgot to mention this one, I forked in order to create the appropriate directory with a .gitignore folder, but figured that was a sloppy solution.

Essentially if you are download the repo and run via Python, the database creation fails because the config subfolder is not present in the database directory.

Apologize if this has already been fixed, but looking through recent commits I don't see anything to suggest it has been.

**Comment by lejacobroy** [comment]
I see!
I usually run it with docker-compose where I map the config folder to a host folder.
It should be fixed now
