### ISSUE TITLE
getting error when trying to pull image

### ISSUE THREAD

**Issue by guycobb2** [lejacobroy/Tidalrr#6]
im no docker guru, so this is likely something i'm doing incorrectly.  but i keep getting a pull access denied.  can anyone shed some light on what im likely doing wrong?

docker run
  -d
  --name='Tidalrr'
  --net='bridge'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="BitLord"
  -e HOST_CONTAINERNAME="Tidalrr"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -p '3010:3001/tcp'
  -v '/mnt/user/appdata/tidalrr/config':'/app/tidalrr/database/config':'rw'
  -v '/mnt/cache_nvme/downloads/tidal-dl/':'/app/download':'rw'
  -v '/mnt/user/appdata/tidalrr/import':'/app/import':'rw'
  -v '/mnt/user/media/music/':'/path/to/lidarr/folders':'rw' 'lejacobroy/tidalrr'
Unable to find image 'lejacobroy/tidalrr:latest' locally
docker: Error response from daemon: pull access denied for lejacobroy/tidalrr, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

The command failed.

**Comment by mangocat1** [comment]
Try - jacobroyquebec/tidalrr
https://hub.docker.com/r/jacobroyquebec/tidalrr

**Comment by guycobb2** [comment]
> Try - jacobroyquebec/tidalrr https://hub.docker.com/r/jacobroyquebec/tidalrr

Thanks. That did the trick. Now to figure everything else out. No webgui loading when I point to it…..but again, likely my fault. Will have to mess with it when I get a minute.

**Comment by sickify1** [comment]
> > Try - jacobroyquebec/tidalrr https://hub.docker.com/r/jacobroyquebec/tidalrr
> 
> Thanks. That did the trick. Now to figure everything else out. No webgui loading when I point to it…..but again, likely my fault. Will have to mess with it when I get a minute.

See: https://github.com/lejacobroy/Tidalrr/issues/5#issuecomment-1942141419

That seemed to fix it for mangocat, there might be other issues if the database schema doesn't have all the changes that are made in the update from V1 -> V4, but it'll get you started at least.

**Comment by guycobb2** [comment]
Thanks.  I'll see if i can make heads or tails out of this.  I'm sure I have something set wrong in the container profile.  Educated guessing on my part.

![Image 2-14-24 at 5 28 PM](https://github.com/lejacobroy/Tidalrr/assets/66560235/bfa2cb1a-806c-40ea-9f2f-8dc9ea492053)
![Image 2-14-24 at 5 29 PM](https://github.com/lejacobroy/Tidalrr/assets/66560235/26cd081c-1323-414d-b2a5-8d6d6d4d6013)

**Comment by coldiak** [comment]
Hi, i have the same problem with the docker image
any help?
thanks

**Comment by sickify1** [comment]
> Hi, i have the same problem with the docker image any help? thanks

Same issue with the docker image not pulling, or same issue with it not starting? If it's the issue not starting, see my earlier comments.

**Comment by guycobb2** [comment]
> > Thanks. I'll see if i can make heads or tails out of this. I'm sure I have something set wrong in the container profile. Educated guessing on my part.
> > ![Image 2-14-24 at 5 28 PM](https://private-user-images.githubusercontent.com/66560235/304905734-bfa2cb1a-806c-40ea-9f2f-8dc9ea492053.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NTc4ODcsIm5iZiI6MTcwNzk1NzU4NywicGF0aCI6Ii82NjU2MDIzNS8zMDQ5MDU3MzQtYmZhMmNiMWEtODA2Yy00MGVhLTlmMmYtOGRjOWVhNDkyMDUzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwMDM5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODFiYzA2ODFlN2M4ZGVlNzNhZmVhMjU0MTc5ZWQ4ZGM1ZDQwNmMyZjA2NzJkNWRkZGQxODA0NTIzMDJmMGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YwWTD2FE6MtoH6atZ2QaXo2xE8aA583Zf6v-GebCJ8o) ![Image 2-14-24 at 5 29 PM](https://private-user-images.githubusercontent.com/66560235/304905737-26cd081c-1323-414d-b2a5-8d6d6d4d6013.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NTc4ODcsIm5iZiI6MTcwNzk1NzU4NywicGF0aCI6Ii82NjU2MDIzNS8zMDQ5MDU3MzctMjZjZDA4MWMtMTMyMy00MTRkLWIyYTUtOGQ2ZDZkNGQ2MDEzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwMDM5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzAyNGNmOTcxYzRiOTJmZTc5Y2ZjMTQ4NTZmMTg5NTRjN2YyMzg1ZDYwNDYxMTRlYmM0OGZmZjY3OTVjYTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a-tEbHbvjy_sXxgYz3K6WHvicTUfl1N4EaZIz4Gm14o)
> 
> Docker setup looks okay, it should just be editing the database init script, deleting the database file and restarting the docker container.

where should the init.py file reside?  I'm not seeing it anywhere that I think it should be.  any ideas what i'm doing wrong?

<img width="1429" alt="Screenshot 2024-02-14 at 8 45 14 PM" src="https://github.com/lejacobroy/Tidalrr/assets/66560235/78d9df43-cfe7-404e-bd2a-2bba7dcdc8da">
![Image 2-14-24 at 9 10 PM](https://github.com/lejacobroy/Tidalrr/assets/66560235/50eebfae-5e8a-4925-9b0c-421a54ef4951)

**Comment by guycobb2** [comment]
ok, didn't realize the init.py for me had double underscores for the leading and trailing.... i thought it was just a single.  so, was able to nano in after try the doubles and changed line 110 as mentioned.  and lo and behold we have a webui now.  will see if any other issues arise, but thanks for the help thus far. 


<img width="1552" alt="Screenshot 2024-02-14 at 10 00 45 PM" src="https://github.com/lejacobroy/Tidalrr/assets/66560235/46ac86f7-1941-4cd1-b0aa-c693c315adce">

**Comment by guycobb2** [comment]
Ok. Progress made but I’m either not fully understanding the intended usage, I’m not going about the proper workflow or I still need some tweaking on the setup. I have lidarr ip and api setup and let it sync. My assumption was that after that took place it would create a queue of missing content to be pulled from tidal. Here’s some shots of where I’m currently at.

![IMG_3603](https://github.com/lejacobroy/Tidalrr/assets/66560235/cfbff323-438d-467b-b365-560381badd9c)

![IMG_3604](https://github.com/lejacobroy/Tidalrr/assets/66560235/611c1d8e-78ab-44d4-810c-c7f548d3f0de)

![IMG_3605](https://github.com/lejacobroy/Tidalrr/assets/66560235/b5d5ecb9-7516-47bc-956e-82386c2a4998)

![IMG_3606](https://github.com/lejacobroy/Tidalrr/assets/66560235/c530a236-8089-4a59-b83a-6e79ae713289)

**Comment by sickify1** [comment]
> > > Ok. Progress made but I’m either not fully understanding the intended usage, I’m not going about the proper workflow or I still need some tweaking on the setup. I have lidarr ip and api setup and let it sync. My assumption was that after that took place it would create a queue of missing content to be pulled from tidal. Here’s some shots of where I’m currently at.
> > 
> > 
> > Have you gone to the Downloads page and started Downloads? I believe when you sync from Lidarr it does not do an Artist match, just matches albums / tracks, which is why you have no Artists in the DB. If you start downloads it should try and grab all the albums in the DB from Tidal.
> 
> I should have included a screenshot of that too. Yeah, I’ve clicked pretty much every button in attempt to see what it did and to try to get downloads started. Here what I get after hitting the download button.


Huh, I will try a fresh copy of it when I have a chance and see what I get. If you add a Tidal Artist link directly via Add from URL, then do a scan, then do a download, does it actually download anything?

**Comment by guycobb2** [comment]
> Huh, I will try a fresh copy of it when I have a chance and see what I get. If you add a Tidal Artist link directly via Add from URL, then do a scan, then do a download, does it actually download anything?


Yeah, that seems to be doing something. Things are being pulled. Will have to see if it completes them and what it does with them afterwards.

![IMG_3608](https://github.com/lejacobroy/Tidalrr/assets/66560235/41f69bea-7a53-4ed7-af32-d255fd1db749)
![IMG_3609](https://github.com/lejacobroy/Tidalrr/assets/66560235/bd589498-6a5f-411c-84ca-b57f97ab7fe1)
![IMG_3610](https://github.com/lejacobroy/Tidalrr/assets/66560235/37c5dbf9-81ee-4801-8e79-455b311f89f7)
![IMG_3611](https://github.com/lejacobroy/Tidalrr/assets/66560235/97fe9cec-81e4-43e8-937d-1bc4db6d4c44)
![IMG_3612](https://github.com/lejacobroy/Tidalrr/assets/66560235/d8c69082-cb90-4afe-8695-b07a0f27420c)
![IMG_3613](https://github.com/lejacobroy/Tidalrr/assets/66560235/f964e26a-0e06-4923-b824-c46fe0d2b683)
![IMG_3614](https://github.com/lejacobroy/Tidalrr/assets/66560235/63440eef-8b96-42cb-bebf-ffa6a00d7ea1)

**Comment by guycobb2** [comment]
ok, all downloads look to have taken place for the artist that was added manually via the "add from url" method.  what do i need to do to automate them to being moved into my library?  they appear to just be hanging out in the download folder designated by tidalrr.  also, it still doesn't seem to by syncing with lidarr.  hope i can get this sqared away........ so close.

<img width="1552" alt="Screenshot 2024-02-15 at 7 57 43 PM" src="https://github.com/lejacobroy/Tidalrr/assets/66560235/0076fe81-ff23-4596-9292-1057d3df2c1b">
<img width="1552" alt="Screenshot 2024-02-15 at 7 57 23 PM" src="https://github.com/lejacobroy/Tidalrr/assets/66560235/b348d139-cb1d-4161-9e32-eb60866e5a90">

**Comment by sickify1** [comment]
> ok, all downloads look to have taken place for the artist that was added manually via the "add from url" method. what do i need to do to automate them to being moved into my library? they appear to just be hanging out in the download folder designated by tidalrr. also, it still doesn't seem to by syncing with lidarr. hope i can get this sqared away........ so close.

I tested the Lidarr integration on a fresh install of the newest version, and it does appear to be broken. The albums get added to the database, but do not show up on the albums page.
I'm not sure if it worked for me previously because I manually added all my artists to Tidalrr first, or if something has broken along the way.

As for adding the music to Lidarr, I have been doing manual imports to Lidarr. You could have Tidalrr download to your Lidarr directory, and set the same naming scheme in Tidalrr as what Lidarr uses and they should automatically be detected. However, I have found that lots of the tracks in Tidal do not correspond to an album that Lidarr has, even with all metadata boxes ticked in my lidarr preferences. So unless you want a bunch of "Unknown" tracks in Lidarr, manual import is probably the best bet.

Maybe there is a better way to do it that that, but i've gotten approx ~12,000 tracks processed so far, and likely would have been able to do it faster If i had set up Tidalrr to name the tracks in the way that Lidarr expects them to be.

**Comment by guycobb2** [comment]
know of any way to redownload already downloaded files?  even after deletion, it still shows them as downloaded.

**Comment by lejacobroy** [comment]
The "Sync Lidarr" page is only to match the missing Lidarr albums to Tidal and add them to the Tidalrr DB in "monitored" state.
Then, you should do a scan of monitored content on the "Scans" page.
Once every monitored content is scanned (In this case, missing albums), you can start the download process on the "Downloads" page.

I recommend you previously set the Tidalrr download folder to the Lidarr Library folder, so that the downloads get picked up by Lidarr.
Furthermore, you can tweak the naming convention to follow the same principles.

As for redownloading files, you can just open the Sqlite DB and set every row to downloaded = 0 in tidal_tracks.

**Comment by lejacobroy** [comment]
I've fixed the problem with starting a DB from scratch in https://github.com/lejacobroy/Tidalrr/commit/8b9d92ee2232b50628ef5149c89f8cd7c33d397c

**Comment by mclaughj** [comment]
@lejacobroy can you publish an updated docker image with the DB fix?

**Comment by lejacobroy** [comment]
Sorry about that, my build server was down for a few days and I completely forgot to push a new image.

**Comment by tecbeat** [comment]
Nice! but I also found an error in the UI. I built the Docker image with the database fix and then the UI also worked. However, the "Add" function (http://localhost:3001/actions/add) unfortunately does not work.

```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

 I haven't gotten any further than adding a playlist (that works), but even with a "start download" and "scan" nothing is triggered.

```
Logs
2024-02-25 11:47:51 Starting downloads
LOG: Running job "startDownloads"
2024-02-25 11:47:51 startDownloads
Non-Empty Access Token, logging in
LOG: Job "startDownloads" completed in 0 seconds
```

Have I misunderstood something else or is this actually a mistake?

**Comment by tecbeat** [comment]
Ich habe das neue image geladen und es funktioniert perfekt, habe jedoch noch auf der startseite einen kaputten link gefunden unter "Add". Vielen dank fürs fixen.
