### ISSUE TITLE
make port configurable

### ISSUE THREAD

**Issue by ramonskie** [lejacobroy/Tidalrr#9]
as port 3001 is used by other servers it would be nice to make this configurable.

**Comment by ramonskie** [comment]
it would probably look like this
`port = os.environ.get("WEB_PORT", "3001")`

`app.run(host="0.0.0.0", port=port, debug=debug)`

**Comment by ramonskie** [comment]
created a pr #10

**Comment by guycobb2** [comment]
are you not using docker?  if so it's easy enough to set a port to redirect.  if using something else that doesn't allow that though, then i see how that could be an annoyance.

**Comment by ramonskie** [comment]
yes i'm using docker but its docker on synology. so there are some caveats with the networking.
i tried to set
```
ports:
- 3101-3001
```
but it never reaches the container.
so for these scenarios it would be nice to be able to configure the port.
its also pretty simple as you can see in the pr

**Comment by ramonskie** [comment]
@lejacobroy i noticed you merged #8 but the docker container has not been updated yet.
so the error still persists when using the latest docker image.

**Comment by lejacobroy** [comment]
Sorry about that, my build server was down for a few days and I completely forgot to push a new image.

**Comment by lejacobroy** [comment]
Merged with commit https://github.com/lejacobroy/Tidalrr/commit/2cb5d99e8437b8190ab0db812a1ab2ddc649e8e4
Thank you! 👍
